language: cpp

notifications:
  email: true

os: linux
dist: bionic

env:
  global:
    - TMPDIR=/tmp

jobs:
  include:

    # Clang 3.7
    - name: Clang-3.7
      dist: xenial
      env: CXX=clang++-3.7 BUILD_TYPE=Debug
      addons: &clang37
        apt:
          packages:
            - clang-3.7
    - name: Clang-3.7 Release
      dist: xenial
      env: CXX=clang++-3.7 BUILD_TYPE=Release
      addons: *clang37

    # Clang 3.8
    - name: Clang-3.8 Debug
      dist: xenial
      env: CXX=clang++-3.8 BUILD_TYPE=Debug
      addons: &clang38
        apt:
          packages:
            - clang-3.8
    - name: Clang-3.8 Release
      dist: xenial
      env: CXX=clang++-3.8 BUILD_TYPE=Release
      addons: *clang38

    # Clang 3.9
    - name: Clang-3.9 Debug
      env: CXX=clang++-3.9 BUILD_TYPE=Debug
      addons: &clang39
        apt:
          packages:
            - clang-3.9
    - name: Clang-3.9 Release
      env: CXX=clang++-3.9 BUILD_TYPE=Release
      addons: *clang39

    # Clang 4.0
    - name: Clang-4.0 Debug
      env: CXX=clang++-4.0 BUILD_TYPE=Debug
      addons: &clang40
        apt:
          packages:
            - clang-4.0
    - name: Clang-4.0 Release
      env: CXX=clang++-4.0 BUILD_TYPE=Release
      addons: *clang40

    # Clang 5.0
    - name: Clang-5.0 Debug
      env: CXX=clang++-5.0 BUILD_TYPE=Debug
      addons: &clang50
        apt:
          packages:
            - clang-5.0
    - name: Clang-5.0 Release
      env: CXX=clang++-5.0 BUILD_TYPE=Release
      addons: *clang50

    # Clang 6.0
    - name: Clang-6.0 Debug
      env: CXX=clang++-6.0 BUILD_TYPE=Debug
      addons: &clang60
        apt:
          packages:
            - clang-6.0
    - name: Clang 6.0 Release
      env: CXX=clang++-6.0 BUILD_TYPE=Release
      addons: *clang60

    # Clang 7 (default on Xenial and Bionic images)
    - name: Clang-7 Debug
      env: CXX=clang++ BUILD_TYPE=Debug
    - name: Clang-7 Release
      env: CXX=clang++ BUILD_TYPE=Release

    # Clang 8
    - name: Clang-8 Debug
      env: CXX=clang++-8 BUILD_TYPE=Debug
      addons: &clang8
        apt:
          sources:
          - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main'
            key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          packages:
          - clang-8
    - name: Clang-8 Release
      env: CXX=clang++-8 BUILD_TYPE=Release
      addons: *clang8

    # Clang 9
    - name: Clang-9 Debug
      env: CXX=clang++-9 BUILD_TYPE=Debug
      addons: &clang9
        apt:
          sources:
          - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
            key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          packages:
          - clang-9
    - name: Clang-9 Release
      env: CXX=clang++-9 BUILD_TYPE=Release
      addons: *clang9

    # Clang 10
    - name: Clang-10 Debug
      env: CXX=clang++-10 BUILD_TYPE=Debug
      addons: &clang10
        apt:
          sources:
          - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
            key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          packages:
          - clang-10
    - name: Clang-10 Release
      env: CXX=clang++-10 BUILD_TYPE=Release
      addons: *clang10

    # GCC 5 (default on the Xenial image)
    - name: GCC-5 Debug
      dist: xenial
      env: CXX=g++-5 BUILD_TYPE=Debug
    - name: GCC-5 Release
      dist: xenial
      env: CXX=g++-5 BUILD_TYPE=Release

    # GCC 6
    - name: GCC-6 Debug
      env: CXX=g++-6 BUILD_TYPE=Debug
      addons: &gcc6
        apt:
          packages: g++-6
    - name: GCC-6 Release
      env: CXX=g++-6 BUILD_TYPE=Release
      addons: *gcc6

    # GCC 7 (default on the Bionic image)
    - name: GCC-7 Debug
      env: CXX=g++-7 BUILD_TYPE=Debug
    - name: GCC-7 Release
      env: CXX=g++-7 BUILD_TYPE=Release

    # GCC 8
    - name: GCC-8 Debug
      env: CXX=g++-8 BUILD_TYPE=Debug
      addons: &gcc8
        apt:
          packages: g++-8
    - name: GCC-8 Release
      env: CXX=g++-8 BUILD_TYPE=Release
      addons: *gcc8

    # GCC 9
    - name: GCC-9 Debug
      env: CXX=g++-9 BUILD_TYPE=Debug
      addons: &gcc9
        apt:
          sources:
          - sourceline: ppa:ubuntu-toolchain-r/test
          packages:
          - g++-9
    - name: GCC-9 Release
      env: CXX=g++-9 BUILD_TYPE=Release
      addons: *gcc9

script:
  - cd "${TRAVIS_BUILD_DIR:?}"
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE:?}
  - cmake --build . -- -j2
