name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.PLATFORM.OS }}

    env:
      CC: ${{ matrix.PLATFORM.CC }}
      CXX: ${{ matrix.PLATFORM.CXX }}

    strategy:
      matrix:
        PLATFORM:
          - {
              OS: ubuntu-latest,
              CC: gcc,
              CXX: g++
            }
          - {
              OS: ubuntu-latest,
              CC: clang,
              CXX: clang++
            }
          - {
              OS: macos-latest,
              CC: clang,
              CXX: clang++
            }

        BUILD_CONFIG: [ Release, Debug ]

    steps:
    - uses: actions/checkout@v2

    # main test
    - name: Configure Test
      run: cmake -B ./build -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_CONFIG }}
      working-directory: ${{github.workspace}}

    - name: Build Text
      run: cmake --build ./build --config ${{ matrix.BUILD_CONFIG }}
      working-directory: ${{github.workspace}}

    # examples/basic_audio_player
    - name: Configure 'examples/basic_audio_player'
      run: cmake -B ./build -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_CONFIG }}
      working-directory: ${{github.workspace}}/examples/basic_audio_player

    - name: Build 'examples/basic_audio_player'
      run: cmake --build ./build --config ${{ matrix.BUILD_CONFIG }}
      working-directory: ${{github.workspace}}/examples/basic_audio_player

    # examples/basic_traffic_light
    - name: Configure 'examples/basic_traffic_light'
      run: cmake -B ./build -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_CONFIG }}
      working-directory: ${{github.workspace}}/examples/basic_traffic_light

    - name: Build 'examples/basic_traffic_light'
      run: cmake --build ./build --config ${{ matrix.BUILD_CONFIG }}
      working-directory: ${{github.workspace}}/examples/basic_traffic_light

    # examples/debug_logger_interface
    - name: Configure 'examples/debug_logger_interface'
      run: cmake -B ./build -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_CONFIG }}
      working-directory: ${{github.workspace}}/examples/debug_logger_interface

    - name: Build 'examples/debug_logger_interface'
      run: cmake --build ./build --config ${{ matrix.BUILD_CONFIG }}
      working-directory: ${{github.workspace}}/examples/debug_logger_interface

    # examples/snippets
    - name: Configure 'examples/snippets'
      run: cmake -B ./build -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_CONFIG }}
      working-directory: ${{github.workspace}}/examples/snippets

    - name: Build 'examples/snippets'
      run: cmake --build ./build --config ${{ matrix.BUILD_CONFIG }}
      working-directory: ${{github.workspace}}/examples/snippets
