name: MSBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.PLATFORM.OS }}

    env:
      SOLUTION_FILE_PATH: ${{ matrix.PLATFORM.SOLUTION_FILE_PATH }}

    strategy:
      matrix:
        PLATFORM:
          - {
              OS: windows-2019,
              SOLUTION_FILE_PATH: projects\premake\ffsm2-vs-2019.sln
            }
          - {
              OS: windows-2022,
              SOLUTION_FILE_PATH: projects\premake\ffsm2-vs-2022.sln
            }

        BUILD_CONFIG: [ Release, Debug ]
        BUILD_PLATFORM: [ 32, 64 ]

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@main

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.BUILD_CONFIG}} /p:Platform=${{matrix.BUILD_PLATFORM}} ${{env.SOLUTION_FILE_PATH}}

    - name: Test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: "binaries/test-17-${{matrix.BUILD_CONFIG}}-${{matrix.BUILD_PLATFORM}}.exe"
